---

- name: "check username"
  fail:
    msg: "All users require a name."
  when: user.name is undefined

- name: "{{ user.name }} : create group"
  group:
    name: "{{ user.name }}"

- name: "{{ user.name }} : create user"
  user:
    name: "{{ user.name }}"
    state: present
    group: "{{ user.name }}"
    shell: /bin/bash
    generate_ssh_key: yes
    update_password: always
    password: x
    ssh_key_bits: 4096
    ssh_key_comment: "{{ user.name }}@{{ fqdn }}"
    ssh_key_type: rsa

- name: "{{ user.name }} : enforce permissions on home directory"
  file:
    path: "/home/{{ user.name }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0700
    state: directory
